sudo: false

language: perl

perl:
  - "5.20"
#  - "5.18"
#  - "5.16"
#  - "5.14"
#  - "5.12"
#  - "5.10"
#  - "5.8"

os:
  - linux
#  - osx

addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu trusty contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    packages:
      - erlang-nox

cache:
  apt: true
  directories:
    - $HOME/.cache

env:
  global:
    - RABBITMQ_VERSION=3.7.4
    - RABBITMQ_DOWNLOAD_URL="https://github.com/rabbitmq/rabbitmq-server/releases/download/v$RABBITMQ_VERSION/rabbitmq-server-generic-unix-$RABBITMQ_VERSION.tar.xz"
    - RABBITMQ_TAR="rabbitmq-$RABBITMQ_VERSION.tar.xz"
    - PATH=$HOME/.local/bin:$PATH
    - MQSSLHOST=localhost
    - MQSSLUSERNAME=guest
    - MQSSLPASSWORD=guest
    - MQSSLCACERT="$TRAVIS_BUILD_DIR/travis/certs/ca_certificate.pem"
    - MQSSLVERIFYHOST=0
    - MQSSLVERIFYPEER=0

before_install:
  - $TRAVIS_BUILD_DIR/travis/before_install

install:
  - if [ ! -d "$HOME/.cache" ]; then mkdir "$HOME/.cache"; fi
  - if [ -s "$HOME/.cache/$RABBITMQ_TAR" ]; then echo "[INFO] found cached $RABBITMQ_TAR file"; else wget -O "$HOME/.cache/$RABBITMQ_TAR" "$RABBITMQ_DOWNLOAD_URL"; fi
  - tar -C "$TRAVIS_BUILD_DIR" -xvf "$HOME/.cache/$RABBITMQ_TAR"
  - sed -e "s#TRAVIS_DIR#$TRAVIS_BUILD_DIR#g" "$TRAVIS_BUILD_DIR/travis/rabbitmq.conf.travis" > "$TRAVIS_BUILD_DIR/travis/rabbitmq.conf"

before_script:
  - /bin/sh -c "RABBITMQ_PID_FILE=$TRAVIS_BUILD_DIR/rabbitmq.pid RABBITMQ_CONFIG_FILE=$TRAVIS_BUILD_DIR/travis/rabbitmq $TRAVIS_BUILD_DIR/rabbitmq_server-$RABBITMQ_VERSION/sbin/rabbitmq-server &"
  - /bin/sh "$TRAVIS_BUILD_DIR/rabbitmq_server-$RABBITMQ_VERSION/sbin/rabbitmqctl" wait "$TRAVIS_BUILD_DIR/rabbitmq.pid"
  - /bin/sh "$TRAVIS_BUILD_DIR/rabbitmq_server-$RABBITMQ_VERSION/sbin/rabbitmqctl" status
  - /bin/sh "$TRAVIS_BUILD_DIR/rabbitmq_server-$RABBITMQ_VERSION/sbin/rabbitmq-plugins" enable rabbitmq_management

script:
  - $TRAVIS_BUILD_DIR/travis/script
